project:
  type: website

website:
  title: "EV Charging vs Gas Costs Over 3 Years"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Graphs
        menu:
          - href: plot-1.qmd
            text: Average Costs Graph
      - text: Individual Vehicle Analysis
        menu:
          - href: mustang-comparison.qmd
            text: Ford Mustang Mach-E vs Ford Mustang
          - href: ioniq-comparison.qmd
            text: Hyundai Ioniq 5 vs Hyundai Tucson
          - href: F-150-comparison.qmd
            text: Ford F-150 Lightning vs Ford F-150
      - href: sources.qmd
        text: Sources
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true